#define visionRange 10
#define cohesionFactor 0.005
#define avoidanceDistance 2
#define avoidanceFactor 0.3
#define avoidObstructionDistance 3
#define avoidObstructionFactor 0.1
#define vipMinDistance 3
#define vipCohesionMultiplier 0.01
#define vipSeparationMultiplier 0.1
#define vipAlignmentMultiplier 0.01
#define vipCircleRadius 5
#define vipCircleNumPoints 360
#define vipBoundingDistance 7
#define velocityPollingRate 2000
#define testing 1
#define timeScale 60
