#define visionRange 10
#define cohesionFactor 0.005
#define avoidanceDistance 2
#define avoidanceFactor 0.1
#define avoidObstructionDistance 3
#define avoidObstructionFactor 0.2
#define vipMinDistance 3
#define vipCohesionMultiplier 0.01
#define vipSeparationMultiplier 0.5
#define vipAlignmentMultiplier 0.02
#define vipCircleRadius 5
#define vipCircleNumPoints 360
#define vipBoundingDistance 7
#define velocityPollingRate 2
#define testing 1
#define timeScale 60
